app/part_creation/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField, IntegerField
from wtforms.validators import DataRequired, EqualTo


class NewPartTypeForm(FlaskForm):
    part_name = StringField('Part Name', validators=[DataRequired()])
    submit = SubmitField('Save Name')

app/part_creation/__init__.py
from flask import Blueprint

bp = Blueprint('part_creation', __name__, template_folder="templates")

from app.part_creation import routes

app/part_creation/routes.py
from app.extensions import db
from app.part_creation import bp
from app.part_creation.forms import NewPartTypeForm
from app.default.models import Batch, Step, Field, PartType
from flask import current_app, render_template, request, flash, redirect, url_for, abort
from flask_login import login_required
import os


@bp.route('/create-part-type', methods=['GET', 'POST'])
@login_required
def create_part_type():
    """The page to create a part type"""

    form = NewPartTypeForm()
    part_type_id = request.args.get("part_type_id")
    part_type = PartType.query.filter_by(id=part_type_id).first()
    # Create a list of steps for the part
    steps = Step.query.filter_by(part_type_id=part_type_id).all()
    steps.sort(key=lambda step: step.step_number)

    if form.validate_on_submit():
        part_type.part_name = form.part_name.data
        db.session.commit()

    # Fill in the part name form to the current part name
    form.part_name.data = part_type.part_name

    return render_template('create-part-type.html',
                           part_type=part_type,
                           steps=steps,
                           form=form)


@bp.route('/new-part-type', methods=['POST'])
@login_required
def new_part_type():
    part_type = PartType(part_name="New Part")
    db.session.add(part_type)
    db.session.commit()
    return redirect(url_for('part_creation.create_part_type', part_type_id=part_type.id))


@bp.route('/edit-step', methods=['GET', 'POST'])
@login_required
def edit_step():
    """The page to edit a step for a part"""

    try:
        part_type_id = request.args.get("part_type_id")
        step_id = request.args.get("step_id")
    except:
        abort(400)
        return
    # Send the user back if the part is uneditable
    if step_id is None or part_type_id is None:
        abort(400)
        return

    part_type = PartType.query.get_or_404(part_type_id)

    if Batch.query.filter_by(part_type_id=part_type_id).first() is not None:
        flash("Parts already exist for this part type, and it can no longer be edited.", category="top")
        return redirect(request.referrer)
    step = Step.query.get_or_404(step_id)
    fields = Field.query.filter_by(step_id=step_id).all()
    # Form is an image upload
    if request.method == 'POST':
        # Save the step info
        step.step_title = request.form['stepTitle']
        step.step_instructions = request.form['stepInstructions']

        # Check if a CSV upload is required
        if 'importCsvCheckbox' in request.form:
            step.csv_upload = True
        else:
            step.csv_upload = False
        db.session.commit()

        # Upload the image
        if 'image' in request.files:
            image = request.files['image']
            # Check the image has the correct file extension
            fn, file_extension = os.path.splitext(image.filename)
            if file_extension not in current_app.config['ALLOWED_EXTENSIONS']:
                flash("Incorrect file extension", category="top")
                return redirect(request.referrer)
            # Create the directory if it doesn't exist
            directory = '/'.join([current_app.config['UPLOAD_FOLDER'], part_type.part_name])
            if not os.path.exists(directory):
                os.makedirs(directory)
            filename = "step" + str(step.step_number) + file_extension
            # Delete the image if one already exists
            if os.path.isfile('/'.join([directory, filename])):
                try:
                    os.remove('/'.join([directory, filename]))
                except OSError:
                    pass
            # Save the image
            image.save('/'.join([directory, filename]))
            # Save the location of the image to the database for retrieval
            step.step_image = '/'.join(["/static/images", part_type.part_name, filename])

        db.session.commit()

    nav_bar_title = str(part_type.part_name) + " - " + "Step " + str(step.step_number)
    return render_template('step.html',
                           nav_bar_title=nav_bar_title,
                           part_type=part_type,
                           step=step,
                           fields=fields)


@bp.route('/addstep', methods=['POST'])
@login_required
def add_step():
    """Adds a new step for a part"""

    part_type_id = request.form["part_type_id"]

    # Check that a batch hasn't been created with this part type
    if Batch.query.filter_by(part_type_id=part_type_id).first() is not None:
        flash("Parts already exist for this part type, and it can no longer be edited.", category="top")
        return redirect(request.referrer)

    steps = Step.query.filter_by(part_type_id=part_type_id).all()

    # Find the next step number
    # = 1 if there are no steps
    if len(steps) == 0:
        new_step_number = 1
    else:
        new_step_number = max(s.step_number for s in steps) + 1
    # Create the default Step title
    step_title = "Step " + str(new_step_number)
    step_instructions = ""
    step = Step(part_type_id=part_type_id,
                step_number=new_step_number,
                step_title=step_title,
                step_instructions=step_instructions)
    db.session.add(step)
    db.session.commit()
    return redirect(request.referrer)


@bp.route('/deletestep', methods=['POST'])
@login_required
def delete_step():
    part_type_id = request.form["part_type_id"]
    steps = Step.query.filter_by(part_type_id=part_type_id).all()
    # Check that a batch hasn't been created with this part type
    if Batch.query.filter_by(part_type_id=part_type_id).first() is not None:
        flash("Parts already exist for this part type, and it can no longer be edited.", category="top")
        return redirect(request.referrer)

    if len(steps) == 0:
        return redirect(request.referrer)
    else:
        # Delete the final step
        steps.sort(key=lambda step: step.step_number)
        last_step = steps[-1]
        db.session.delete(last_step)
        db.session.commit()
        return redirect(request.referrer)


@bp.route('/savedatafield', methods=['POST'])
@login_required
def save_field():
    """ The POST request to add a data field when editing a step"""
    field_name = request.json.get("field_name")
    step_id = request.json.get("step_id")
    batch_wide = request.json.get("batch_wide")
    f = Field(field_name=field_name, step_id=step_id, batch_wide=batch_wide)
    db.session.add(f)
    db.session.commit()
    return '', 201


@bp.route('/deletedatafield', methods=['POST'])
@login_required
def delete_field():
    """ The POST request to delete a data field during creation of a step"""
    field_name = request.json.get("field_name")
    step_id = request.json.get("step_id")
    field = Field.query.filter_by(field_name=field_name, step_id=step_id).first()
    db.session.delete(field)
    db.session.commit()
    return '', 201

app/part_creation/templates/create-part-type.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Create part type</h1>

        <form action="" method="post">

            {{ form.hidden_tag() }}
            <p>
                {{ form.part_name.label(class_="form-label") }}
                {{ form.part_name(size=32, class="form-control") }}
                {{ form.submit(class_="btn btn-primary mt-2") }}
                {% for error in form.part_name.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            {{ form.csrf_token }}

        </form>


        <h2> Steps </h2>
        <form action="{{ url_for('part_creation.add_step') }}" method="post">
            <input type="hidden" name="part_type_id" value="{{ part_type.id }}"/>
            <input type="submit" value="Create Step" class="btn btn-primary"/>
        </form>
        <!--Create the list of existing steps-->
        {% for s in steps %}
            {% if p != None %}
                <a href="{{ url_for('part_creation.edit_step') }}?part_type_id={{ part_type.id }}&step_id={{ s.id }}">
                    {{ s.step_number }} - {{ s.step_title }}<br></a>
            {% endif %}
        {% endfor %}

        <form action="{{ url_for('part_creation.delete_step') }}" method="post">
            <input type="hidden" name="part_type_id" value="{{ part_type.id }}"/>
            <input type="submit" class="btn btn-danger" value="Delete Last Step"/>
        </form>
    </div>

{% endblock %}

app/part_creation/templates/createparttype.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Create part type</h1>

        <form action="" method="post">

            {{ form.hidden_tag() }}
            <p>
                {{ form.part_name.label }}<br>
                {{ form.part_name(size=32) }} {{ form.submit() }}
                {% for error in form.part_name.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            {{ form.csrf_token }}

        </form>


        <h2> Steps </h2>
        <form action="{{ url_for('part_creation.add_step') }}" method="post">
            <input type="hidden" name="part_type_id" value="{{ part_type.id }}"/>
            <input type="submit" value="Create Step"/>
        </form>
        <!--Create the list of existing steps-->
        {% for s in steps %}
            {% if p != None %}
                <a href="{{ url_for('part_creation.edit_step') }}?part_type_id={{ part_type.id }}&step_id={{ s.id }}">
                    {{ s.step_number }} - {{ s.step_title }}<br></a>
            {% endif %}
        {% endfor %}

        <form action="{{ url_for('part_creation.delete_step') }}" method="post">
            <input type="hidden" name="part_type_id" value="{{ part_type.id }}"/>
            <input type="submit" value="Delete Last Step"/>
        </form>
    </div>

{% endblock %}

app/part_creation/templates/step.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-2">
        <form method="get" action="{{ url_for('part_creation.create_part_type') }}">
            <input type="hidden" name="part_type_id" value="{{ part_type.id }}"/>
            <input type="submit" class="btn btn-primary" value="< Back to Create Part screen"/>
        </form>
        <div class="container">
            <form id="stepInfoForm" name="stepInfo" action="" method="post" enctype="multipart/form-data">
                <input type="hidden" name="formName" value="stepInfo"/>
                <div class="row">

                    <div id="stepInfoCreationForm" class="col-4">
                        <h2>Step Info</h2>
                        <label for="stepTitleInput" class="form-label">Step Title</label>
                        <input type="text"
                               id="stepTitleInput"
                               class="form-control"
                               name="stepTitle"
                               value="{{ step.step_title }}">
                        <label for="stepInstructionsInput">Step Instructions</label>
                        <textarea
                                id="stepInstructionsInput"
                                class="form-control"
                                name="stepInstructions">{{ step.step_instructions }}</textarea>
                    </div>

                    <div id="dataCreationForm" class="col-4">
                        <h2>Data</h2>
                        <p class="form-text">Data to be requested from the user during this step</p>

                        <input type="checkbox" id="allPartsCheckbox" Value="allParts">
                        <label for="allPartsCheckbox">Same value for all parts in batch</label>



                        <div class="row">
                            <div class="col-auto">
                                <input type="text" class="form-control" id="newField" placeholder="New Field Name...">
                            </div>
                            <div class="col-auto">
                                <button type="button" class="btn btn-primary" onclick="addToList()">Add</button>
                            </div>
                        </div>

                        <ul id="fieldList">
                            {% for f in fields %}
                                {% if f != None %}
                                    <li class="fieldLi">{{ f.field_name }}</li>
                                {% endif %}
                            {% endfor %}
                        </ul>

                        <input type="checkbox" id="importCsvCheckbox" name="importCsvCheckbox" Value="importCsv"
                                {% if step.csv_upload %}
                               checked="checked"
                                {% endif %}
                        >
                        <label class="mt-5" for="importCsvCheckbox">Request CSV upload for this step</label>
                    </div>


                    <div id="uploadImageForm" class="col-4">
                        <h2>Image</h2>
                        <input type="hidden" name="formName" value="uploadImage"/>
                        <span class="btn btn-default btn-file">
                            <input type="file" name="image">
                        </span>
                        <div id="uploadImagePreview" class="stepCreationColumn">
                            {% if step.step_image %}
                                <img id="uploadImage" src="{{ step.step_image }}">
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <input type="submit" class="btn btn-primary mt-4" id="stepFormSubmit" value="Save">
                </div>

            </form>
        </div>


        <br>


    </div>
    <script>
        /**
         * Control the behaviour of the list of data fields
         *
         */
        const fieldList = document.getElementsByClassName("fieldLi");
        for (let i = 0; i < fieldList.length; i++) {
            let delBtn = document.createElement("BUTTON");
            const delTxt = document.createTextNode("Delete");
            delBtn.setAttribute("type", "button");
            delBtn.className = "close btn btn-sm btn-danger";
            delBtn.appendChild(delTxt);
            fieldList[i].appendChild(delBtn);
        }

        // Click on a close button to hide the current list item
        const close = document.getElementsByClassName("close");
        for (let i = 0; i < close.length; i++) {
            close[i].onclick = function () {
                //Hide the element
                const div = this.parentElement;
                const len = (div.innerText.length - delTxt.length);
                let fieldName = div.innerText.substring(0, len); //Remove the "delete" that appears
                // Remove line breaks that were appearing in fieldName for some reason
                fieldName = fieldName.replace(/(\r\n\t|\n|\r\t)/gm, "");
                div.style.display = "none";
                //Send the POST request to delete the database entry
                const xhttp = new XMLHttpRequest();
                xhttp.open("POST", "/deletedatafield", true);
                xhttp.setRequestHeader('Content-Type', 'application/json');
                const jsonString = '{ "field_name": "' + fieldName + '" , "step_id": "{{step.id}}"}';
                xhttp.send(jsonString);
            }
        }


        // Create a new list item when clicking on the "Add" button, and save it to the database
        function addToList() {
            const li = document.createElement("li");
            const inputValue = document.getElementById("newField").value;
            const t = document.createTextNode(inputValue);
            li.appendChild(t);
            li.className = "fieldLi";
            if (inputValue === '') {
                alert("Please enter a name for the data to be recorded");
            } else {
                document.getElementById("fieldList").appendChild(li);
            }
            document.getElementById("newField").value = "";

            const delBtn = document.createElement("BUTTON");
            const txt = document.createTextNode("Delete");
            delBtn.setAttribute("type", "button");
            delBtn.className = "close btn btn-sm btn-danger";
            delBtn.appendChild(txt);
            li.appendChild(delBtn);

            for (i = 0; i < close.length; i++) {
                close[i].onclick = function () {
                    const div = this.parentElement;
                    div.style.display = "none";
                }
            }
            const allParts = document.getElementById("allPartsCheckbox").checked;
            const xhttp = new XMLHttpRequest();
            xhttp.open("POST", "/savedatafield", true);
            xhttp.setRequestHeader('Content-Type', 'application/json');
            xhttp.send(
                '{ "field_name": "' + inputValue + '" , ' +
                '"step_id": "{{step.id}}" , ' +
                '"batch_wide":' + allParts + ' }');
        }

    </script>
{% endblock %}